### ISSUE TITLE
Remove include guards

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore-lib#21]
I cannot see why they are necessary. I do not find any global variables that need to be protected from being overwritten.

https://github.com/bitpay/bitcore-lib/blob/master/index.js#L7

**Comment by Levino** [comment]
So this is why it was introduced: https://github.com/bitpay/bitcore/issues/1164

But there should be a better way. I am trying to reproduce the error with this example: https://github.com/Levino/understand-instanceof

Can someone help me reproduce it?

**Comment by Levino** [comment]
Okay, now I get it. But then one should remove the "instanceOf" calls instead of introducing include guards.

**Comment by Levino** [comment]
So in principle one just wants a sanity check there. I mean if the check fails one throws an error anyhow. So why not just add a String to the PublicKey class elements? Something like this here: https://github.com/Levino/understand-instanceof/tree/solution

Should one not be happy then? I agree that people could pass a very old implementation of a Publickey into a new version of bitcore. But maybe it is better to allow this, than to mess this much with the require part of everything.

**Comment by Levino** [comment]
Another solution could be to make PublicKey (and so on) their own packages and require them with:
```js
var PublicKey = require('bitcore-publickey')
```
Am I wrong?

**Comment by Levino** [comment]
Mentioning this https://github.com/bitpay/bitcore-lib/pull/4

**Comment by fanatid** [comment]
If you have correct `package.json` now (use `peerDependencies` in modules such as `bitcore-mnemonic`) or use npm@3 that install modules maximally flat most likely you willn't have problems with version guard. But in general I agree, instanceof check should be replaced.

**Comment by Levino** [comment]
@fanatid Thank you for pointing this out. Very interesting. Here is a read on peerDependencies.

So I understand that moving this line to "peerDependencies" should solve all problems: https://github.com/bitpay/bitcore-mnemonic/blob/master/package.json#L41

Include guards can stay, even though I would prefer a warning instead of an error.

**Comment by fanatid** [comment]
Yep, I think that should solve problem.
At least I put `bitcore-lib` to `peerDependencies` in [coloredcoinjs-lib](https://github.com/fanatid/coloredcoinjs-lib/blob/master/package.json#L64) and use this library in [chromanode](https://github.com/chromaway/chromanode/blob/master/package.json#L52). All fine, on npm@2 and npm@3

**Comment by Levino** [comment]
Just tested it. Requiring [this version](https://github.com/Levino/bitcore-message) of bitcore-message and bitcore 0.13.6 in one application gives a nice error.

```
npm ERR! Linux 3.19.0-33-generic
npm ERR! argv "/home/levin/.nvm/versions/node/v4.2.2/bin/node" "/home/levin/.nvm/versions/node/v4.2.2/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package bitcore-lib@0.13.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer bitcore-message@1.0.2 wants bitcore-lib@^0.13.7
```

**Comment by paulkernfeld** [comment]
I would really appreciate this, because I'm finding it difficult to develop locally using `npm link`. This is because `npm link` may result in multiple copies of bitcore-lib. I understand that this is intended to keep users from getting tricked by instanceof, but this is preventing my project from running in a situation where I'm not even depending on bitcore-lib directly. I think the include guards have the potential to disrupt builds on any project that has bitcore-lib anywhere in the dependency hierarchy.

**Comment by Levino** [comment]
@paulkernfeld I agree totally. It is very un-npm-style to even think of introducing them. Really bad style. Take this fork if you want only warnings and not exceptions https://github.com/bitpay/bitcore-lib

**Comment by paulkernfeld** [comment]
@Levino thanks! I think your link is broken; isn't that the main bitcore-lib repository?

**Comment by paulkernfeld** [comment]
I believe that @Levino is referring satoshipay/bitcore-lib, which changes this to a warning.

Unfortunately, this doesn't fix my problem, because a dependency that I don't control (webcoin) still depends on the original version of bitcore-lib. :(

To the bitcore team: what would it take to fix this? Would removing the instanceof calls be enough?

**Comment by paulkernfeld** [comment]
In the mean time, here is a fun and sketchy workaround for anyone who is interested! I probably don't need to say that this is not the ideal solution.

```javascript
// kekeke
global._bitcore = undefined
var Script = require('bitcore-lib').Script
var Transaction = require('bitcore-lib').Transaction
global._bitcore = undefined
```

**Comment by Levino** [comment]
@paulkernfeld Yes, sorry, took the wrong one. I corrected the link in my comment above. Deleting the include guards works also. See also here: https://github.com/bitpay/bitcore/issues/1188#issuecomment-93633477

**Comment by wzrdtales** [comment]
+1
Totally agree to this, this module is completely broken through this, taken how easy this error will throw when adding just one single dependency.

@braydonf 
Can you explain why the bitpay team has decided to use global variables? I also had my experiments with them in modules and threw them out very quickly again, but they are really only useful for final applications, but not for modules.

**Comment by matiu** [comment]
> Totally agree to this, this module is completely broken through this, taken how easy this error will throw when adding just one single dependency.

no, it is not.

Because Bitcore-lib use `is instance of`, see for example https://github.com/bitpay/bitcore-lib/blob/master/lib/address.js#L102, it needs to have only one declaration of each class.

If you run into the error, you can fix it doing the following:

1- Check were your ware including bitcore-lib: In the root of you project run:
  `fing . -type d -name bitcore-lib`

2- You must have 2 or more results.  In order to fix the error you need to have *only one* result.

3- Leave only one, and remove the others, but deleting the directly and adding a symlink to the one you left.

That should fix the error. I understand it is a bit frustrating and probably there are better ways to solve this in the code, but this procedure should work on all cases.

**Comment by Levino** [comment]
> Because Bitcore-lib use is instance of, see for example https://github.com/bitpay/bitcore-lib/blob/master/lib/address.js#L102, it needs to have only one declaration of each class.

Maybe one should not check for "instance of"? I would say this is very very bad practice. It might be something that works in C++, Go or whatever. But in JavaScript you just "try your best" with whatever you get. And if some dumb user gives you an object that does not fit the requirements, it is his bad. BOOOM exception. The checks you are mentioning have to ALSO be removed of course.

**Comment by braydonf** [comment]
Considering that `instanceof` assertions for `PublicKey` have found bugs (https://github.com/indutny/elliptic/issues/17) that could lead to the loss of funds, the extra safety is worth it.

**Comment by Levino** [comment]
Aha. This is helpful @braydonf But then is there not a better way? How exactly does the test help?

**Comment by braydonf** [comment]
Moved to: https://github.com/bitpay/bitcore-lib/issues/67
