### ISSUE TITLE
Why the rename?

### ISSUE THREAD

**Issue by jprichardson** [bitpay/bitcore-lib#3]
Why the rename (and repo change) from [`bitcore`](https://www.npmjs.com/package/bitcore) to [`bitcore-lib`](https://www.npmjs.com/package/bitcore-lib)?

**Comment by braydonf** [comment]
The goal is to clear space in the bitcore repository to focus on bitcore running a full node with a cli utility, and still be able to only require the base constructors PrivateKey, PublicKey, Transaction and others from bitcore-lib.

**Comment by eordano** [comment]
Hey @braydon, @gasteve:

I'd like you to reconsider reverting this change. Two main reasons:

- The first one is technical. It's a huge and unexpected interface break for people that depend on `bitcore` on `npm`. They will now be getting a full load of extra functionality they did not expect.

- There's a number of projects (bitcore community) that should be consulted about this bold move -- or at least alerted! This doesn't feel like the right way to do open source.

I'd like to see a more detailed case for *why* is this rename happening, because one sentence doesn't explain this huge awkward move...

**Comment by braydonf** [comment]
Ping @bitjson

**Comment by bitjson** [comment]
Hey @eordano, Thanks for the input and all your work in the ecosystem. Those are both good points, I hope I can clarify:

- The `bitcore-lib` package is exposed by `bitcore`, so projects requiring `bitcore` via npm shouldn't notice any change by upgrading. (One of the easiest migrations we've had in a while! :smiley:) The same is true for Bower users.

- We're still polishing some of the work we've been doing to make bitcore easier for new bitcoin developers, but we wanted to begin making this change early on github so the community can be involved.

If you know of any projects using Bitcore in a non-standard way, I'd definite appreciate a ping – the more use-cases we can take into account, the better Bitcore becomes.

You'll be hearing a lot more from us about the new features in bitcore this week. Thanks!

**Comment by JustinDrake** [comment]
I, for one, really appreciate this change. Cheers!
